pipeline {
    agent any
    tools {
        maven "m3"
    }
    stages {
        stage('push-to-feature-branch') {
            when {
                branch pattern: "ft-cbtrfdev*"
            }
            stages {
                stage("build") {
                    dir("examples/cloudbank/backend-springboot") {
                        sh "mvn clean package"
                    }
                }
                stage("run tests") {
                    dir("examples/cloudbank/backend-springboot") {
                        echo "Running tests"
                    }
                }
            }
        }
        stage("merge-to-dev-branch") {
            when {
                branch 'dev'
            }
            stages {
                stage("build") {
                    steps {
                        dir("examples/cloudbank/backend-springboot") {
                            sh "mvn clean package"
                        }
                    }

                }
                stage("notify") {
                    steps {
                        echo "New changes merged into DEV ${GIT_COMMIT}"
                    }
                }

            }
        }
    }
}

