pipeline {
    agent any
    environment {
        DATABASENAME="${GIT_BRANCH.split("-")[0].toLowerCase()}"
    }
    stages {
        stage("details") {
        // Assumption: Branch names start with CBTRFDEVXXX-SUMMARY
        // CBTRFDEV is a CloudBank Transfer Microservice Development branch
        // CBTRFDEVXXX becomes the database name for development
            steps {
                echo "************************************************"
                echo "* ENVIRONMENT"
                echo "************************************************"
                sh "printenv"
                echo ""
                echo "************************************************"
                echo "* $DATABASENAME"
                echo "************************************************"
                sh "ls $WORKSPACE"
                echo "************************************************"
            }
        }
        stage('create-feature-branch') {
        // Only triggered on create-branch (BUILD_NUMBER == 1)
            when {
                allOf {
                    not { changeRequest target: "main" };
                    not { branch "main" };
                    equals expected: "3", actual: env.BUILD_NUMBER
                }

            }
               stages {
                    stage("generate-yaml-file") {
                        steps {
                            echo "Generating YAML file to generate"
                            dir("examples/cloudbank/jenkins/backend-dev/scripts") {
                                sh "./generate-yaml-file.sh $DATABASENAME"
                            }

                            echo "DONE"
                        }
                    }
                    stage("create-database") {
                        steps {
                            echo "Creating Single-Instance Database $DATABASENAME"
                            create_database()
                            echo "DONE"
                        }
                    }
                    stage("setup-database") {
                        steps {
                            echo "Setting up SIDB $DATABASENAME"
                            setup_database()
                            echo "DONE"
                        }
               }
            }

        }
        stage('push-to-branch') {
        // Only triggered on pushed commits (BUILD_NUMBER > 1)
            when {
                not { changeRequest target: "main" };
                not { branch "main" };
            }
            stages {
                stage("build-backend") {
                    steps {
                        echo "Commit found"
                        echo "Build# ${env.BUILD_NUMBER}"
                        setup_database()
                    }
                }

            }


        }

        stage("merge-to-main") {
            when {
                changeRequest target: "main"
            }
            steps {
                echo "Pull Request $BRANCH_NAME"
            }
        }
    }
}

def setup_database() {
    timeout(5) {
        waitUntil {
            script {
                withKubeCredentials(
                    kubectlCredentials: [[
                        caCertificate: '',
                        clusterName: "cluster-cwz7kgdbhgq",
                        contextName: '',
                        credentialsId: 'kubectl-token',
                        namespace: "kube-system",
                        serverUrl: "https://132.226.124.76:6443"
                    ]]) {
                    def r = sh script: "kubectl get singleinstancedatabase $DATABASENAME -o 'jsonpath={.status.status}'", returnStdout: true
                    print r
                    return (r == "Healthy")
                }
            }
        }
    }
    echo "Database now exists and setup can begin."
    withKubeCredentials(kubectlCredentials: [[
        caCertificate: '',
        clusterName: "cluster-cwz7kgdbhgq",
        contextName: '',
        credentialsId: "kubectl-token",
        namespace: "kube-system",
        serverUrl: "https://132.226.124.76:6443"
        ]]) {
            echo "Configuring LoadBalancer..."
            sh "kubectl --type=merge -p '{\"spec\":{\"loadBalancer\": true}}' patch singleinstancedatabase $DATABASENAME"
            echo "DONE"
        }
}

def create_database() {
    dir("$WORKSPACE/run") {
        withKubeCredentials(kubectlCredentials: [[
        caCertificate: '',
        clusterName: "cluster-cwz7kgdbhgq",
        contextName: '',
        credentialsId: "kubectl-token",
        namespace: "kube-system",
        serverUrl: "https://132.226.124.76:6443"
        ]]) {
            sh "kubectl apply -f sidb-create.yaml"
            sh "kubectl --type=merge -p '{\"spec\":{\"loadBalancer\": true}}' patch singleinstancedatabase $DATABASENAME"
        }
    }
}